spring.application.name=config-server
server.port=8888
#Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
spring.cloud.config.server.git.uri=https://github.com/krrobincook/config-server
spring.cloud.config.server.git.username=krrobincook
spring.cloud.config.server.git.password=${GITHUB_TOKEN}
spring.cloud.config.server.git.default-label=main